import React from "react";
import Script from "next/script";

function contact() {
  return (
    <div>
      <Script>{`alert("Welcome to contact page")`}</Script>I am contact page
    </div>
  );
}

export default contact;

export const metadata = {
  title: "Learning Next.js on contact",
  description: "Generated by create next app",
};
