import React from "react";

function about() {
  return <div>I am About page</div>;
}

export default about;

export const metadata = {
  title: "Learning Next.js on About",
  description: "Generated by create next app",
};
